### ISSUE TITLE
aep-132-request-required-params should ignore path parameters

### ISSUE THREAD

**Issue by toumorokoshi** [aep-dev/aep-openapi-linter#8]
Today, the rule fails for the following schema:

```yaml
  /publishers/{publisher}/books/{book}/editions:
    get:
      description: List method for book-edition
      operationId: book-edition.list
      parameters:
      - description: ""
        in: path
        name: publisher
        required: true
        schema:
          type: string
      - description: ""
        in: path
        name: book
        required: true
        schema:
          type: string
      - description: ""
        in: query
        name: max_page_size
        required: false
        schema:
          type: integer
      - description: ""
        in: query
        name: page_token
        required: false
        schema:
          type: string
```

Note that the query parameters are not required, but the path parameters of the parents are (since the publisher/book is required to find the appropriate collection).

I believe the rule should be changed to allow required path parameters.
